services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: "sh src/start.sh"
